# Docs: https://black.readthedocs.io/en/stable/
[tool.black]
line-length = 88                                                                # Max line length
target-version = ["py310"]                                                      # Target Python 3.10

# Docs: https://beta.ruff.rs/docs/
[tool.ruff]
line-length = 88                                                                # Max line length
target-version = "py310"                                                        # Target Python 3.10
